import { apiClient } from './client';

// Top level, alongside /regularisation. Leave is its own resource on the
// server; the app presents it as its own tab.
const BASE = '/leave';

export type LeaveType = 'casual' | 'sick' | 'earned' | 'unpaid';
export type LeaveStatus = 'pending' | 'approved' | 'rejected' | 'cancelled';

export const LEAVE_TYPES: LeaveType[] = ['casual', 'sick', 'earned', 'unpaid'];

/** What each type is for, in the words an employee would use. */
export const LEAVE_TYPE_LABEL: Record<LeaveType, string> = {
  casual: 'Casual',
  sick: 'Sick',
  earned: 'Earned',
  unpaid: 'Unpaid',
};

export type LeaveRequest = {
  id: string;
  employeeId: string;
  employeeName?: string;
  storeCode: string;
  storeName?: string | null;
  leaveType: LeaveType;
  startDate: string;
  endDate: string;
  halfDay: boolean;
  /** Calendar days, generated by the database. `0.5` for a half day. */
  totalDays: number | null;
  reason: string;
  status: LeaveStatus;
  createdAt: string;
  decidedAt: string | null;
  decidedBy: string | null;
  decisionNote: string | null;
};

export type NewLeave = {
  leave_type: LeaveType;
  start_date: string;
  end_date: string;
  half_day?: boolean;
  reason: string;
};

/**
 * Days taken and pending this calendar year, per type.
 *
 * Deliberately not a balance. Nothing on the server holds an entitlement, so
 * a "days remaining" figure would be invented — the screen says "taken" and
 * means it.
 */
export type LeaveSummary = {
  employeeId: string;
  year: number;
  taken: Record<LeaveType, number>;
  pending: Record<LeaveType, number>;
  takenTotal: number;
  pendingTotal: number;
};

/**
 * A reviewer gets their scoped queue here; everyone else gets their own
 * applications. The employee app is always the second case.
 *
 * The shared list envelope: `data` is the array, paging rides in `meta`.
 * Pending first, then start date newest first — already the order the screen
 * wants, but it is re-sorted client-side anyway so a server change cannot
 * quietly reorder the list.
 */
export async function getMyLeave(limit = 50) {
  const res = await apiClient.get<{ success: true; data: LeaveRequest[] }>(BASE, {
    params: { limit },
  });
  return res.data.data ?? [];
}

export async function getLeaveSummary(year?: number) {
  const res = await apiClient.get<{ success: true; data: LeaveSummary }>(`${BASE}/summary`, {
    params: year ? { year } : undefined,
  });
  return res.data.data;
}

export async function applyForLeave(input: NewLeave) {
  const res = await apiClient.post<{ success: true; data: LeaveRequest }>(BASE, input);
  return res.data.data;
}

/** Withdraw one's own request. Only works while it is still pending. */
export async function cancelLeave(id: string) {
  const res = await apiClient.post<{ success: true; data: LeaveRequest }>(`${BASE}/${id}/cancel`, {});
  return res.data.data;
}
