import { apiClient } from './client';

// Top level, alongside /regularisation. Leave is its own resource on the
// server; the app presents it as its own tab.
const BASE = '/leave';

/** Paid or unpaid, and nothing else -- the only distinction payroll acts on. */
export type LeaveType = 'paid' | 'unpaid';
export type LeaveStatus = 'pending' | 'approved' | 'rejected' | 'cancelled';

export const LEAVE_TYPES: LeaveType[] = ['paid', 'unpaid'];

/**
 * Catalogue KEYS rather than English.
 *
 * These sat here as finished strings, which read as part of the wire contract
 * when they are really display text. A key keeps the mapping next to the type
 * it describes while leaving the WORDS to the language layer -- and a
 * module-level constant holding text would freeze whichever language loaded
 * first, which is the bug this avoids.
 */
export const LEAVE_TYPE_LABEL_KEY = {
  paid: 'leaveType.paid',
  unpaid: 'leaveType.unpaid',
} as const;

/** What each one means for the day, said plainly on the form. */
export const LEAVE_TYPE_HINT_KEY = {
  paid: 'leaveType.paidHint',
  unpaid: 'leaveType.unpaidHint',
} as const;

export type LeaveRequest = {
  id: string;
  employeeId: string;
  employeeName?: string;
  storeCode: string;
  storeName?: string | null;
  leaveType: LeaveType;
  startDate: string;
  endDate: string;
  halfDay: boolean;
  /** Calendar days, generated by the database. `0.5` for a half day. */
  totalDays: number | null;
  reason: string;
  status: LeaveStatus;
  createdAt: string;
  /** Set when an unpaid day was actually worked, and what it earned back. */
  workedOn: string | null;
  compOffEarned: number;
  compOffUsedAt: string | null;
  decidedAt: string | null;
  decidedBy: string | null;
  decisionNote: string | null;
};

export type NewLeave = {
  leave_type: LeaveType;
  start_date: string;
  end_date: string;
  half_day?: boolean;
  reason: string;
};

/**
 * Leave taken in ONE MONTH, plus the eleven before it.
 *
 * Monthly because that is how leave is discussed and approved -- an annual
 * running total answers "how many days in August" only by subtraction.
 * `compOffOutstanding` is counted apart from days taken: it is leave OWED, and
 * folding it in would make somebody who came in look like somebody who did not.
 */
export type LeaveMonth = {
  month: string;
  taken: Record<LeaveType, number>;
  pending: Record<LeaveType, number>;
  takenTotal: number;
  pendingTotal: number;
};

export type LeaveSummary = LeaveMonth & {
  employeeId: string;
  compOffEarned: number;
  compOffOutstanding: number;
  byMonth: LeaveMonth[];
};

/**
 * A reviewer gets their scoped queue here; everyone else gets their own
 * applications. The employee app is always the second case.
 *
 * The shared list envelope: `data` is the array, paging rides in `meta`.
 * Pending first, then start date newest first — already the order the screen
 * wants, but it is re-sorted client-side anyway so a server change cannot
 * quietly reorder the list.
 */
export async function getMyLeave(limit = 50) {
  const res = await apiClient.get<{ success: true; data: LeaveRequest[] }>(BASE, {
    params: { limit },
  });
  return res.data.data ?? [];
}

/** `month` is YYYY-MM. Omitted means the current one. */
export async function getLeaveSummary(month?: string) {
  const res = await apiClient.get<{ success: true; data: LeaveSummary }>(`${BASE}/summary`, {
    params: month ? { month } : undefined,
  });
  return res.data.data;
}

/**
 * Record that a day of UNPAID leave was actually worked, earning it back.
 *
 * Unpaid only, and only once the leave is approved -- working a paid day earns
 * nothing extra because it was already being paid for.
 */
export async function markWorkedDuringLeave(id: string, workedOn: string, halfDay = false) {
  const res = await apiClient.post<{ success: true; data: LeaveRequest }>(`${BASE}/${id}/worked`, {
    worked_on: workedOn,
    half_day: halfDay,
  });
  return res.data.data;
}

export async function applyForLeave(input: NewLeave) {
  const res = await apiClient.post<{ success: true; data: LeaveRequest }>(BASE, input);
  return res.data.data;
}

/** Withdraw one's own request. Only works while it is still pending. */
export async function cancelLeave(id: string) {
  const res = await apiClient.post<{ success: true; data: LeaveRequest }>(`${BASE}/${id}/cancel`, {});
  return res.data.data;
}
